format = """
[░▒▓](#a3aed2)\
$os\
$username\
[](bg:#769ffe fg:#a3aed2)\
$directory\
[](fg:#769ffe bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$python\
$nix_shell\
[](fg:#212736)\
\n$character"""

[directory]
style = "bg:#769ffe fg:#090c10"
format = "[ $path ]($style)"

[git_branch]
symbol = " "
style = "bg:#394260 fg:#e0af68"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:#394260 fg:#f7768e"
format = '[$all_status$ahead_behind ]($style)'

[nix_shell]
symbol = " "
style = "bg:#212736 fg:#7dcfff"
format = '[$symbol$state ]($style)'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
